
#ifndef __HARMAN_ADAS_AGRAPHIC_ERROR_H__
#define __HARMAN_ADAS_AGRAPHIC_ERROR_H__





#define GUIDELINE_ERROR_LOADPROGRAM_FAILED			1001
#define GUIDELINE_ERROR_WHEELBASEOUTOFRANGE			1002
#define GUIDELINE_ERROR_ANGELOUTOFRANGE			1003

#endif // __HARMAN_ADAS_AGRAPHIC_ERROR_H__
