/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.5.
* Used org.franca.core 0.9.1.201412191134.
*
* generated by Voice CodeGen Version: R1_v1.3.0
* generated on: Tue Mar 07 13:22:52 CST 2017
*/
#ifndef V2_ORG_GENIVI_NODESTATEMANAGER_CONSUMER_HPP_
#define V2_ORG_GENIVI_NODESTATEMANAGER_CONSUMER_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/Types.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v2 {
namespace org {
namespace genivi {
namespace NodeStateManager {

class Consumer {
public:
    virtual ~Consumer() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
};

const char* Consumer::getInterface() {
    return ("org.genivi.NodeStateManager.Consumer");
}

CommonAPI::Version Consumer::getInterfaceVersion() {
    return CommonAPI::Version(2, 1);
}


} // namespace NodeStateManager
} // namespace genivi
} // namespace org
} // namespace v2

namespace CommonAPI {
}


// Compatibility
namespace v2_1 = v2;

#endif // V2_ORG_GENIVI_NODESTATEMANAGER_CONSUMER_HPP_
