//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Adas
//  @ File Name : IGraphicsImpl.h
//  @ Date : 2/16/2015
//  @ Author : 
//
//


#if !defined(_IGRAPHICSIMPL_H)
#define _IGRAPHICSIMPL_H

#include "foundation.h"

class CBaseGraphicsImpl : public CMessageSubHandler
{
public: // typedef enum struct

public: // method
	virtual void initialize(Int32 x, Int32 y, UInt32 uiW, UInt32 uiH ) = 0;
	virtual void unInitialize() = 0;

	virtual void update() = 0;
	//virtual void showCamera(void* pData) = 0;
	virtual BOOLEAN isCurPendingRequest() = 0;
	virtual void onCurPendingRequest() = 0;

protected:// method

private: // method

protected: // data

private:// data

};

#endif  //_IGRAPHICSIMPL_H
