/**
 * generated by DCIF CodeGen Version: R2_v2.3.0
 * generated on: Tue Aug 01 13:37:53 CST 2017
 */
#include <iostream>
#include <memory>
#include <unistd.h>
#include "CAdasManagerGWMv2.h"
#include "MessageForQueue.h"
using namespace std;
using namespace Harman::Adas::AProject::GWMV2MH;

int main(int argc, char **argv) {
    CAdasManagerGWMv2::getInstance()->start();
    CAdasManagerGWMv2::getInstance()->pushMessage(new MessageForQueue(0,0, string("456")));
    CAdasManagerGWMv2::getInstance()->join();
    
    getchar();
    return 0;
}
