/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.5.
* Used org.franca.core 0.9.1.201412191134.
*
* generated by Voice CodeGen Version: R1_v1.3.0
* generated on: Tue Mar 07 13:22:52 CST 2017
*/
#ifndef V0_ORG_HARMAN_FORD_rearviewcamclient_PROXY_BASE_HPP_
#define V0_ORG_HARMAN_FORD_rearviewcamclient_PROXY_BASE_HPP_

#include <v0/org/harman/ford/rearviewcamclient.hpp>


#include <v0/org/harman/ford/rearviewcamclient_types.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>

#include <CommonAPI/Attribute.hpp>
#include <CommonAPI/Proxy.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v0 {
namespace org {
namespace harman {
namespace ford {

class rearviewcamclientProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::ObservableReadonlyAttribute<::v0::org::harman::ford::rearviewcamclient_types::GearRvrse_D_Actl_struct> GearRvrse_D_ActlAttribute;


    /**
     * description: No Information Available
     */
    virtual GearRvrse_D_ActlAttribute& getGearRvrse_D_ActlAttribute() = 0;


};

} // namespace ford
} // namespace harman
} // namespace org
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_ORG_HARMAN_FORD_rearviewcamclient_PROXY_BASE_HPP_
