//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Ford-LCIS
//  @ File Name : PDCError.h
//  @ Date : 2016-11-22
//  @ Author : Guofeng.lu@harman.com
//
//


#if !defined(_PDCERROR_H)
#define _PDCERROR_H

#include "PDCState.h"

class PDCError : public PDCState {
};

#endif  //_PDCERROR_H
