//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Ford-LCIS
//  @ File Name : PDCStateStop.h
//  @ Date : 2016-11-22
//  @ Author : Guofeng.lu@harman.com
//
//


#if !defined(_PDCSTATESTOP_H)
#define _PDCSTATESTOP_H

#include "PDCState.h"

class PDCStateStop : public PDCState {
};

#endif  //_PDCSTATESTOP_H
