//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Ford-LCIS
//  @ File Name : PDCState.h
//  @ Date : 2016-11-22
//  @ Author : Guofeng.lu@harman.com
//
//


#if !defined(_PDCSTATE_H)
#define _PDCSTATE_H


class PDCState {
public:
	virtual void vShow() = 0;
	virtual void vHide() = 0;
	virtual void vError() = 0;
	virtual void vPause() = 0;
};

#endif  //_PDCSTATE_H
