//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Ford-LCIS
//  @ File Name : FordPDCTest.h
//  @ Date : 2016-11-22
//  @ Author : Guofeng.lu@harman.com
//
//


#if !defined(_FORDPDCTEST_H)
#define _FORDPDCTEST_H
#include "../../../src-gen/consumes/v0/org/harman/ford/visualparkassist_types.hpp"
using namespace v0::org::harman::ford;
//#include "../CAMB_PDCConsumerHandler.hpp"
#include "../graphiclib/GraphicVPAFord.h"
#include "../PDCServiceFord.h"
#include "../core/CRunableService.h"

class FordPDCTest : public CRunableService {
public:
	FordPDCTest(PDCServiceFord* pPDCServiceFord,GraphicVPAFord* pGraphicVPAFord);
    void update();
	void setup();
private:
	void vSendPDCState();
	//AMB_PDCConsumerHandler m_testAMBPDC;
	void vUsecase_blockstate();
	void vUsecase_NormalWalkThrough();
	void vUsecase_FrontWalkThrough();
	void vUsecase_RearWalkThrough();
	void vUsecase_LeftWalkThrough();
	void vUsecase_RightWalkThrough();
	void vUsecase_VDT_Forward_straight();
	void vUsecase_VDT_Rearward_straight();
	void vUsecase_VDT_Rearward_LtNegative();
	void vUsecase_VDT_Rearward_RtPositive();	
	void vUsecase_VDT_Forward_RtPositive();
	void vUsecase_VDT_Forward_LtNegative();
	void vUsecase_VDT_OFF();
	void vUsecase_VDT_LaunchControl();
	PDCServiceFord* m_PDCServiceFord;
	GraphicVPAFord* m_GraphicVPAFord;

};


#endif  //_PAMANAGER_H

