//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Adas
//  @ File Name : CSVCaptureThread.h
//  @ Date : 2/16/2015
//  @ Author : 
//
//


#if !defined(_CSVCAPTURETHREAD_H)
#define _CSVCAPTURETHREAD_H

#include "CCaptureThread.h"

class CSVCaptureThread : public CCaptureThread
{
};

#endif  //_CSVCAPTURETHREAD_H
