//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Ford-LCIS
//  @ File Name : FordPDCClientMsgObjs.h
//  @ Date : 2016-11-22
//  @ Author : Guofeng.lu@harman.com
//
//


#if !defined(_FORDPDCCLIENTMSGOBJS_H)
#define _FORDPDCCLIENTMSGOBJS_H


class FordPDCClientMsgObjs {
};

#endif  //_FORDPDCCLIENTMSGOBJS_H
