//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Ford-LCIS
//  @ File Name : PDCfactory.h
//  @ Date : 2016-11-22
//  @ Author : Guofeng.lu@harman.com
//
//


#if !defined(_PDCFACTORY_H)
#define _PDCFACTORY_H
//#include "VPAServiceStubImpl.hpp"
//#include "PDCServiceProxy.h"
#include "PDCServiceFord.h"
//using namespace v0::com::harman::ParkAssist;
//using namespace v1::com::harman::ParkAssist;

class PDCFactory {
public:
    static PDCFactory* getInstance();
    static void 				delInstance();
    PDCServiceFord* vSetup();
    virtual ~PDCFactory();
private:
    PDCFactory();
    static PDCFactory*  m_pInstance;
    //VPAServiceStubImpl* m_pVPAStubImpl;
    //PDCServiceProxy* m_pPDCServiceProxy;
};


#endif  //_PAMANAGER_H
