//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Ford-LCIS
//  @ File Name : PDCGraphicFord.h
//  @ Date : 2016-11-22
//  @ Author : Guofeng.lu@harman.com
//
//


#if !defined(_PDCGRAPHICFORD_H)
#define _PDCGRAPHICFORD_H

#include "PDCGraphic.h"
#include "GraphicVPAFord.h"

class PDCGraphicFord
{
public:
	enum ePDCGraphicState {
		eDISABLED,
		eENABLED
	};
	enum ePDCDayNightMode {
		eNOTSET_NIGHTMOD,
		eDAY,
		eNIGHT
	};
	enum ePDCDedicateMode {
		eNOTSET_DEDIMOD,
		eDEDICATE,
		eSHARESCREEN
	};
	enum ePDCSegment {
		eNOTSET_SEGMENT,
		ePOS1,
		ePOS2
	};

	PDCGraphicFord(IGraphicPDC* pIGraphicPDC);
	~PDCGraphicFord();
private:
	IGraphicPDC* m_pIGraphicPDC;
	ePDCDayNightMode m_ePDCDayNightMode ;
	ePDCDedicateMode m_ePDCDedicateMode ;
	ePDCGraphicState m_ePDCGraphicState ;
	ePDCSegment m_ePDCSegment ;
};

#endif  //_PDCGRAPHICFORD_H
