//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ScreenShot.h
//  @ Date : 2017/3/8 ÐÇÆÚÈý
//  @ Author : 
//
//


#if !defined(_SCREENSHOT_H)
#define _SCREENSHOT_H
#include <screen/screen.h>

class ScreenShot
{
public:
	ScreenShot();
	~ScreenShot();
	int iInit();
	int iDumptoBuffer(char* pbuf);
	int iDumptoBMP(const char* pDumpToFile, const char* pDumpFromBuf);
	int iGetScreenWidth() {return m_iWidth;};
	int iGetScreenHeight(){return m_iHeight;};
private:
	screen_context_t screen_ctx;
	screen_display_t screen_disp;
	screen_display_t *screen_displays;
	screen_pixmap_t screen_pix;
	screen_buffer_t screen_buf;
	char *m_pointer;
	int m_stride;
	int m_iWidth;
	int m_iHeight;
};

#endif  //_SCREENSHOT_H
